### ISSUE TITLE
src/pipeline_pre.py 2 Line:554, embedding lookup has key not found error.

### ISSUE THREAD

**Issue by lkfo415579** [boschresearch/BCAI_kaggle_CHAMPS#1]
Command : `python pipline_pre.py 2`

It seems to be like, there is a new type of bond in testdata, which never appears in the train data. 

what embedding index should it takes? using 0? (the "None" index?)

And it is like only one special key error appears.. "1JHN-H_1.0_1.0_1.0_0.0-N_2.0_2.0_1.0_1.0" in bonds['type_2']

```
Loading data...
Sorting...
Adding embeddings and scaling...
Loading test data...

File "/home/kaggle/BCAI_kaggle_CHAMPS/src/pipeline_pre.py", line 554, in <lambda>
bonds["type_index_" + str(t)] = bonds["type_" + str(t)].apply(lambda x : embeddings[('bond',t)][x])

KeyError: '1JHN-H_1.0_1.0_1.0_0.0-N_2.0_2.0_1.0_1.0'
```

**Comment by tiendatnguyen-vision** [comment]
I overcome the issue by replacing "embeddings[('bond', t)][x] by a custom function below: 
def bond_embedding(t, x): 
        try: 
            emb =  embeddings[('bond',t)][x]
            return emb
        except: 
            return 0

So the error line is rewritten as: 
bonds["type_index_" + str(t)] = bonds["type_" + str(t)].apply(lambda x : bond_embedding(t, x))
Not sure if using the index 0 ("None") is correct or not for the Keyerror.
